# -*- coding: utf-8 -*-
"""오픈소스_데이터_최종 완성의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NhFH4L3IfbFw4XMXprB1PfnS7m-_fRsy
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

!pip install folium

import folium

from google.colab import drive 
drive.mount('/content/drive')

# 위도
latitude = 36.800311566824234

# 경도
longitude = 127.07497430585461

m = folium.Map(location=[latitude, longitude],
               zoom_start=16,
               width=800,
               height=600
               )

folium.Marker([latitude, longitude],
              popup='선문대학교',
              tooltip='선문대학교 아산캠퍼스').add_to(m)
m

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/데이터/소상공인시장진흥공단_상가(상권)정보_충남_202203.csv')
df.head(3)

pd.Series(df.columns)

df['행정동명'].unique()

sub_df = df.loc[df['행정동명'].isin(['탕정면','신안동','불당동'])]
sub_df.head(3)

sub_df[['위도', '경도', '상호명']]

from folium.plugins import MarkerCluster

m = folium.Map(
    location=[latitude, longitude],
    zoom_start=15
)

coords = sub_df[['위도', '경도']]

marker_cluster =MarkerCluster().add_to(m)

for lat, long in zip(coords['위도'], coords['경도']):
    folium.Marker([lat,long], icon=folium.Icon(color="green")).add_to(marker_cluster)
m

import requests
import json

# 충청남도 행정구역 json raw파일(githubcontent)
r = requests.get('https://raw.githubusercontent.com/raqoon886/Local_HangJeongDong/master/hangjeongdong_%EC%B6%A9%EC%B2%AD%EB%82%A8%EB%8F%84.geojson')
c = r.content
Chungnam_geo = json.loads(c)
Chungnam_geo

import pandas as pd

Chungnam = pd.read_csv("/content/drive/MyDrive/데이터/소상공인시장진흥공단_상가(상권)정보_충남_202203.csv")

# 필요한 컬럼 정보만
Chungnam = Chungnam[['시군구명', '상권업종대분류명', '행정동명', '상권업종중분류명', '위도', '경도']]
Chungnam

import matplotlib.pyplot as plt
import seaborn as sns

# 한글 폰트 설정
plt.rcParams['font.family'] = 'NanumGothic'

# 정렬
Chungnam['상권업종대분류명'].value_counts().index

plt.figure(figsize=(12,6))
sns.countplot(y=Chungnam['상권업종대분류명'], order=Chungnam['상권업종대분류명'].value_counts().index)
plt.title('천안시 상권 업종의 수')
plt.show()

"""**천안에 가장 많이 분포하고 있는 것은 소매, 다음으로는 음식으로 나온다.**"""

Chungnam_3 = Chungnam.loc[Chungnam['행정동명'].isin(['탕정면','신안동','불당동'])]
Chungnam_3.head(3)

Chungnam_3['상권업종대분류명'].value_counts().index

plt.figure(figsize=(12,6))
sns.countplot(y=Chungnam_3['상권업종대분류명'], order=Chungnam_3['상권업종대분류명'].value_counts().index)
plt.title('탕정면, 신안동, 불당동의 업종의 수')
plt.show()

Chungnam_3_food = Chungnam_3.loc[Chungnam_3['상권업종대분류명'].isin(['음식'])]
Chungnam_3_food

plt.figure(figsize=(12, 10))
sns.countplot(y=Chungnam_3_food['상권업종중분류명'], order=Chungnam_3_food['상권업종중분류명'].value_counts().index)
plt.title('탕정면, 신안동, 불당동의 음식 분류')
plt.show()

plt.figure(figsize=(10,5))
plt.title('불당동, 신안동, 탕정면의 커피점/카페 수')
Chungnam_3_coffee = (Chungnam_3_food.loc[Chungnam_3_food['상권업종중분류명'] == '커피점/카페']
                     .groupby('행정동명')['상권업종대분류명']
                     .count()
                     .plot(kind='barh'))
Chungnam_3_coffee

#천안시 음식점 수 
Chungnam_groupby = Chungnam.loc[Chungnam['상권업종대분류명']== '음식'].groupby('시군구명')['상권업종대분류명'].count().sort_values()
Chungnam_groupby

m2 = folium.Map(
    location=[36.800311566824234, 127.07497430585461],
    zoom_start=15, 
    tiles='cartodbpositron' #타일 설정
)

folium.Marker([latitude, longitude],
              popup='선문대학교',
              tooltip='선문대학교 아산캠퍼스').add_to(m2)

folium.GeoJson(Chungnam_geo,
               name='지역구').add_to(m2)

marker_cluster =MarkerCluster().add_to(m2)

for lat, long in zip(coords['위도'], coords['경도']):
    folium.Marker([lat,long], icon=folium.Icon(color="green")).add_to(marker_cluster)

m2.choropleth(geo_data= Chungnam_geo,
             data =Chungnam_groupby,
             fill_color='YlOrRd',
             fill_opacity=0.5,
             line_opacity=0.2,
             key_on = 'properties.sggnm',
             legend_name="천안시 지역구별 음식점 업종 수"
             )
m2

# 충청남도 대학의 위경도 
# 전문대, 사이버대학 제외 / 제1 캠퍼스만 포함

# 공주대학교
latitude2 = 36.46949856793522
longitude2 = 127.14075117019483 

# 건양대학교
latitude3 = 36.18212509865622
longitude3 = 127.11014281657724

# 금강대학교
latitude4 = 36.30541520199865
longitude4 = 127.19649322234903

# 나사렛대학교
latitude5 = 36.794986053946886
longitude5 = 127.1190811033399 

# 남서울대학교
latitude6 = 36.90732653563801
longitude6 = 127.14371696974972 

# 백석대학교
latitude7= 36.83903680877866
longitude7 = 127.18583169296453

# 순천향대학교
latitude8 = 36.76999313403953
longitude8 = 126.93180932550064 

# 중부대학교
latitude9 = 36.19242938588509
longitude9 = 127.44849921678333

# 한서대학교
latitude10 = 36.68997903772218
longitude10 = 126.58426563510248

# 호서대학교
latitude11 = 36.827371542781094
longitude11 = 127.18321415894826

m3 = folium.Map(
    location=[36.800311566824234, 127.07497430585461],
    zoom_start=8.5, 
    tiles='cartodbpositron' #타일 설정
)

folium.GeoJson(Chungnam_geo,
               name='지역구').add_to(m3)

folium.Marker([latitude, longitude],
              popup='선문대학교',
              tooltip='선문대학교 아산캠퍼스').add_to(m3)

folium.Marker([latitude2, longitude2],
              popup='공주대학교').add_to(m3)

folium.Marker([latitude3, longitude3],
              popup='건양대학교').add_to(m3)

folium.Marker([latitude4, longitude4],
              popup='금강대학교').add_to(m3)

folium.Marker([latitude5, longitude5],
              popup='나사렛대학교').add_to(m3)

folium.Marker([latitude6, longitude6],
              popup='남서울대학교').add_to(m3)

folium.Marker([latitude7, longitude7],
              popup='백석대학교').add_to(m3)

folium.Marker([latitude8, longitude8],
              popup='순천향대학교').add_to(m3)

folium.Marker([latitude9, longitude9],
              popup='중부대학교').add_to(m3)

folium.Marker([latitude10, longitude10],
              popup='한서대학교').add_to(m3)

folium.Marker([latitude11, longitude11],
              popup='호서대학교').add_to(m3)

m3.choropleth(geo_data= Chungnam_geo,
             data =Chungnam_groupby,
             fill_color='YlOrRd',
             fill_opacity=0.5,
             line_opacity=0.2,
             key_on = 'properties.sggnm',
             legend_name="충청남도 상권과 대학 위치 비교"
             )
              
m3